services:
  - type: web
    name: binti-events-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "5000"
      - key: PESAPAL_API_URL
        value: https://sandbox.pesapal.com
      - key: USE_PESAPAL_MOCK
        value: "false"
      - key: FRONTEND_URL
        value: https://bintievents.vercel.app
      - key: MONGODB_URI
      - key: PESAPAL_CONSUMER_KEY
      - key: PESAPAL_CONSUMER_SECRET
      - key: PESAPAL_CALLBACK_URL
      - key: MPESA_CONSUMER_KEY
      - key: MPESA_CONSUMER_SECRET
      - key: MPESA_CALLBACK_URL
      - key: MPESA_PASSKEY
      - key: EMAIL_USER
      - key: EMAIL_PASSWORD
      - key: BACKEND_URL
